### PR TITLE
meta/main.yml: CI - Add support for all Fedora images

### PR DESCRIPTION
**Pull request by jharuda**
Signed-off-by: Jakub Haruda <jharuda@redhat.com>

### CODE REVIEW

**Review by richm — APPROVED** [review]
lgtm

**Comment by richm** [comment]
@jharuda please rebase this on top of latest master branch

**Comment by jharuda** [comment]
> @jharuda please rebase this on top of latest master branch

done

**Review by richm — APPROVED** [review]
lgtm

**Pull request merged**
